//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotController.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RotController.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   This application contains the following code : Low level Windows keyboard hook class [Ramunas Geciauskas, http://geciauskas.com]
        ///
        /// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is fur [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ソフトウェアが起動されました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status1 {
            get {
                return ResourceManager.GetString("Status1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定が保存されました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status2 {
            get {
                return ResourceManager.GetString("Status2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   右回転時のキーを設定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status3 {
            get {
                return ResourceManager.GetString("Status3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左回転時のキーを設定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status4 {
            get {
                return ResourceManager.GetString("Status4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自動起動を有効にしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status5 {
            get {
                return ResourceManager.GetString("Status5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイスはハードウェアで制御されています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status6 {
            get {
                return ResourceManager.GetString("Status6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   デバイスはソフトウェアで制御されています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Status7 {
            get {
                return ResourceManager.GetString("Status7", resourceCulture);
            }
        }
    }
}
